// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config';
import config from '../config/env.ts';

export default defineConfig({
	schema: 'schema.prisma',
	migrations: {
		path: 'migrations',
	},
	datasource: {
		url: config.databaseUrl,
	},
});
