name: Continuous Integration

on:
    push:
        branches:
            - "**"
            - "!main"
    pull_request:
        branches:
            - "**"
            - "!main"

jobs:
    changes:
        runs-on: ubuntu-latest
        outputs:
            frontend: ${{ steps.filter.outputs.frontend }}
            backend: ${{ steps.filter.outputs.backend }}
        steps:
            - uses: actions/checkout@v6
            - uses: dorny/paths-filter@v3
              id: filter
              with:
                  filters: |
                      frontend:
                          - './frontend/**'
                      backend:
                          - './backend/**'

    test-backend:
        needs: changes
        if: ${{ needs.changes.outputs.backend == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Node environment
              uses: actions/setup-node@v6
              with:
                  node-version: "24.x"

            - name: Install dependencies
              working-directory: backend
              run: npm ci

            - name: Perform test
              working-directory: backend
              run: npm run test

    test-frontend:
        needs: changes
        if: ${{ needs.changes.outputs.frontend == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup Node environment
              uses: actions/setup-node@v6
              with:
                  node-version: "24.x"

            - name: Install dependencies
              working-directory: frontend
              run: npm ci

            - name: Perform test
              working-directory: frontend
              run: npm run test

run-name: Deploy to ${{ github.head_ref || github.ref_name  }} by @${{ github.actor }}
